### ISSUE TITLE
Scipy 1.12 requires `>= 1.22.4`

### ISSUE THREAD

**Issue by sklam** [AnacondaRecipes/scipy-feedstock#32]
https://github.com/AnacondaRecipes/scipy-feedstock/blob/7b972f185173ee0389061c1257bad83554f84961/recipe/meta.yaml#L38

Scipy 1.12 requires numpy>=1.22.4 otherwise the following warnings are shown:

`UserWarning: A NumPy version >=1.22.4 and <1.29.0 is required for this version of SciPy (detected version 1.22.3)`

**Comment by cbouss** [comment]
solved via repodata hotfix
